
[build.environment]
  NPM_VERSION = "6.14.8"
  NODE_VERSION = "12.16.3"

[build]
  publish = "api-docs/v1/_build/html"
  command = "cd api-docs/v1 && make clean html && cd .. && cd .."

[context.production]
  publish = "api-docs/v1/_build/html"
  command = "cd api-docs/v1 && make clean html && cd .. && cd .."

[context.deploy-preview]
  publish = "api-docs/v1/_build/html"
  command = "cd api-docs/v1 && make clean html && cd .. && cd .."
